# Generated by Django 4.2.2 on 2023-06-09 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_helper', '0006_post_likes_post_stars_star_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='post',
        ),
        migrations.RemoveField(
            model_name='star',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='stars',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Star',
        ),
    ]
