# Generated by Django 4.2.2 on 2023-06-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_helper', '0008_post_likes_post_stars_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='stars',
        ),
        migrations.AddField(
            model_name='reply',
            name='stars',
            field=models.FloatField(default=0),
        ),
    ]
