# Generated by Django 4.2.2 on 2023-06-10 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_helper', '0013_rename_message_reply_reply_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='message',
            new_name='post_message',
        ),
    ]
