# Generated by Django 4.2.2 on 2023-06-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_helper', '0015_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='stars',
        ),
    ]
