# Generated by Django 4.2.2 on 2023-06-11 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework_helper', '0016_remove_reply_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework_helper.reply'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
