# Generated by Django 4.2.2 on 2023-06-11 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework_helper', '0018_alter_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_ratings', to='homework_helper.reply'),
        ),
    ]
