# Generated by Django 4.2.2 on 2023-06-13 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework_helper', '0019_alter_rating_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework_helper.reply'),
        ),
    ]
