# Generated by Django 4.2.2 on 2023-06-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_helper', '0022_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
