# Generated by Django 4.2.2 on 2023-06-19 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_helper', '0024_alter_reply_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_message',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20)]),
        ),
    ]
