# Generated by Django 4.2.2 on 2023-06-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_helper', '0025_alter_post_post_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_message',
            field=models.TextField(),
        ),
    ]
